server:
  port: 5800

spring:
  application:
    name: spring-player-file-service
  redis:
    port: 6379
    host: localhost
    password: 123456
  player:
    minio:
      url: http://localhost:9000
      accessKey: minioadmin
      secretKey: minioadmin
      bucketName: demo
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30

