server:
  port: 7000
eureka:
  instance:
    hostname: fred-pc
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
    use-read-only-response-cache: false