server:
  port: 12000

spring:
  application:
    name: spring-player-sentinel-service
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 1
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: fengy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30

