spring:
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
      - org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration