server:
  port: 5020

spring:
  application:
    name: spring-player-crumb-service
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.159.1:9200
  redis:
    port: 6379
    host: localhost
    password: 123456
  kafka:
    bootstrap-servers: 192.168.159.1:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.github.paganini2008.springplayer.common.logging.kafka.AppLogEntryJsonSerializer
    consumer:
      group-id: applog
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.github.paganini2008.springplayer.common.logging.kafka.AppLogEntryJsonDeserializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30

