server:
  port: 10080

spring:
  player:
    messenger:
      store: redis
  application:
    name: spring-player-messager-service
    swagger:
      enabled: true
  profiles:
    active: email
  redis:
    port: 6379
    host: localhost
    password: 123456
  rabbitmq: 
    host: 192.168.159.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5 
        max-concurrency: 10
        acknowledge-mode: manual
        prefetch: 1
    publisher-confirm-type: correlated
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: fengy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      idle-timeout: 180000
      maximum-pool-size: 20
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  mail:
    host: smtp.tom.com
    username: allyes-tester@tom.com
    password: 12345678
    default-encoding: UTF-8
  kafka:
    bootstrap-servers: 192.168.159.1:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.github.paganini2008.springplayer.messenger.kafka.MessagingEntitySerializer
    consumer:
      group-id: testGroup
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.github.paganini2008.springplayer.messenger.kafka.MessagingEntityDeserializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30



