server:
  port: 5200

spring:
  application:
    name: spring-player-log-service
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.16.150:9200
  redis:
    port: 6379
    host: localhost
    password: 123456
  kafka:
    bootstrap-servers: 192.168.12.51:9092,192.168.12.52:9092,192.168.12.53:9092 # kafka集群信息
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.github.paganini2008.springplayer.logging.common.AppLogEntryJsonSerializer
    consumer:
      group-id: applog
      enable-auto-commit: false
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.github.paganini2008.springplayer.logging.common.AppLogEntryJsonDeserializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 8
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12

