server:
  port: 6100

spring:
  application:
    name: spring-player-id-service
  redis:
    port: 6379
    host: localhost
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://fred-pc:7000/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30

